#!/bin/bash

# save command line arguments
script_id=$1
script_description=$2

if [[ -v BASH_DEV_SCRATCH_DIR ]] ; then
    scratch_dir=${BASH_DEV_SCRATCH_DIR}
    mkdir -p ${scratch_dir}
else
    scratch_dir=$(mktemp --tmpdir=/tmp -d bash_dev_XXXXXXX)
fi

products_dir=./products
mkdir -p ${products_dir}

# define name of result file
script_file=${scratch_dir}/${script_id}.sh
output_file=${scratch_dir}/${script_id}.txt

# copy query from stdin to the query file
echo "# ${script_description}" > ${script_file}
IFS=''; while read line
do
    echo "$line" >> ${script_file}
done

# execute the script on the given data file and save results
bash ${script_file} > ${output_file}

# print the script results
echo
echo "********************************************** CELL ${script_id} ************************************************"
echo
cat ${script_file}
echo "------------------------------------------- ${script_id} OUTPUTS ------------------------------------------------"
echo
cat ${output_file}
echo



